version: "3"

services: 
    app:
        # tells the dockerfile to build
        build: 
            context: .
        ports: 
            - "8000:8000"
        volumes: 
            - ./app:/app
        # wait_for_db is a management cmd that we made
        # migrate runs the databse migrations
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"